# This file was generated by GoReleaser. DO NOT EDIT.
class MinikubeSupport < Formula
  desc "The minikube support tools provides a better integration into your local operating system. "
  homepage "https://github.com/qaware/minikube-support"
  version "0.1.0"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/qaware/minikube-support/releases/download/v0.1.0/minikube-support_0.1.0_darwin_amd64.tar.gz"
    sha256 "fedb7462d30cb1a8cbedd5bb6ef5f59975489717c8412d529531f304ad4c4356"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/qaware/minikube-support/releases/download/v0.1.0/minikube-support_0.1.0_linux_amd64.tar.gz"
    sha256 "86ca6c06bd2ed08f1470d03453e459be8291b9e99f965a05020822ad1e84c3b6"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/qaware/minikube-support/releases/download/v0.1.0/minikube-support_0.1.0_linux_armv6.tar.gz"
    sha256 "d4f4a17b2648c76b8ce5441ff283354540e4b53260513cb70ef3035f64c5d914"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/qaware/minikube-support/releases/download/v0.1.0/minikube-support_0.1.0_linux_arm64.tar.gz"
    sha256 "93516963afdbee3727d4b0d60a529a1c7f3e54a5b530651f79a7171ac5f1f5e6"
  end

  depends_on "mkcert"
  depends_on "minikube"
  depends_on "helm"

  def install
    bin.install "minikube-support"
    bash_completion.install "completions/minikube-support.bash" => "minikube-support"
    zsh_completion.install "completions/minikube-support.zsh" => "_minikube-support"
  end

  test do
    system "#{bin}/minikube-support --version"
  end
end
